[package]
name = "thetadata-proto"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
prost.workspace = true
prost-types.workspace = true
tonic-prost-build.workspace = true
